### ISSUE TITLE
Image needs to be updated because of Certificates.

### ISSUE THREAD

**Issue by phihub** [cw1/docker-webcron#2] opened 2021-10-04 10:14 UTC
Lets Encrypt certificates cannot be verified because of outdated certificates in the image.

**Comment by rfilmyer** [comment] 2021-10-16 00:32
I just ran into this as well, but this shouldn't make sense... the image is working off of `alpine:latest` and is a very, very thin shim over that.

**Comment by rfilmyer** [comment] 2021-10-16 00:35
Sure enough, this is an Alpine Linux/Docker issue:  
https://github.com/alpinelinux/docker-alpine/issues/205
https://github.com/alpinelinux/docker-alpine/issues/206

**Comment by cw1** [comment] 2021-10-26 19:47
As @rfilmyer mentioned the root cause is in the base image, therefor I'll close this issue. But thanks for mentioning.

**Closed as completed by cw1** 2021-10-26 19:47 UTC
